version: "3.8"

services:
  mosquitto:
    image: eclipse-mosquitto:2.0.20
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped

  influxdb:
    image: influxdb:2.7.10
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=my_org
      - DOCKER_INFLUXDB_INIT_BUCKET=farming
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-secret-token
    volumes:
      - influxdb_data:/var/lib/influxdb2
    restart: unless-stopped

  telegraf:
    image: telegraf:1.32.3
    container_name: telegraf
    depends_on:
      - influxdb
      - mosquitto
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.4.0
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped

  nodered:
    image: nodered/node-red
    container_name: nodered
    ports:
      - "1880:1880"
    depends_on:
      - mosquitto
    volumes:
      - nodered_data:/data
    restart: unless-stopped

  sensor_publisher:
    build: ./sensor_publisher
    container_name: sensor_publisher
    depends_on:
      - mosquitto
    restart: always

volumes:
  influxdb_data:
  grafana_data:
  nodered_data:
